### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lilcsz** [azael1337/Discordapp-TokenGrabber#17]
Traceback (most recent call last):
  File "main.py", line 220, in <module>
    Grabber().start()
  File "main.py", line 189, in start
    self.grabToken()
  File "main.py", line 144, in grabToken
    for file in os.listdir(location):
FileNotFoundError: [WinError 3] Sistem belirtilen yolu bulamıyor: 'C:\Users\hıhoyu0ğo9uy9p\AppData\Roaming\Discord\Local Storage\leveldb'

**Comment by NineTailedTaviChan-alt** [comment]
Try reinstalling your Discord from the [official site](https://discord.com/api/download?platform=win) and make sure that there is a folder under that directory. Your system seems to be missing it
